/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CursorContainer: typeof import('./../../src/components/CursorContainer.vue')['default']
    Header: typeof import('./../../src/components/Header.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NPagination: typeof import('naive-ui')['NPagination']
    PostCard: typeof import('./../../src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../../src/components/SideBar.vue')['default']
    Toc: typeof import('./../../src/components/Toc.vue')['default']
    Typewriter: typeof import('./../../src/components/Typewriter.vue')['default']
  }
}
