/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogInfo: typeof import('./../../src/components/BlogInfo.vue')['default']
    CursorContainer: typeof import('./../../src/components/CursorContainer.vue')['default']
    Header: typeof import('./../../src/components/Header.vue')['default']
    MobileBar: typeof import('./../../src/components/MobileBar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NTag: typeof import('naive-ui')['NTag']
    PostCard: typeof import('./../../src/components/PostCard.vue')['default']
    PostFooter: typeof import('./../../src/components/PostFooter.vue')['default']
    PostHeader: typeof import('./../../src/components/PostHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../../src/components/SideBar.vue')['default']
    Toc: typeof import('./../../src/components/Toc.vue')['default']
    Typewriter: typeof import('./../../src/components/Typewriter.vue')['default']
  }
}
